package pt.cmolhao.web.documentacao_hab_social_programa_apoio_arrendamento_1_fase;

import com.haulmont.cuba.gui.screen.*;
import pt.cmolhao.entity.DocumentacaoHabSocialProgramaApoioArrendamento1Fase;

@UiController("cmolhao_DocumentacaoHabSocialProgramaApoioArrendamento1Fase.browse")
@UiDescriptor("documentacao-hab-social-programa-apoio-arrendamento1-fase-browse.xml")
@LookupComponent("documentacaoHabSocialProgramaApoioArrendamento1FasesTable")
@LoadDataBeforeShow
public class DocumentacaoHabSocialProgramaApoioArrendamento1FaseBrowse extends StandardLookup<DocumentacaoHabSocialProgramaApoioArrendamento1Fase> {
}